@extends('layouts.app')
@section('page_title', __('inventory.warehouse.index_title'))
@section('page_eyebrow', __('inventory.eyebrow'))
@section('content')
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-3"><form method="GET" class="erp-filter-bar"><input class="form-control" name="q" value="{{ request('q') }}" placeholder="{{ __('inventory.warehouse.search_placeholder') }}"><button class="btn btn-outline-secondary">{{ __('inventory.warehouse.search') }}</button></form><a href="{{ route('inventory.warehouses.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-2"></i>{{ __('inventory.warehouse.add') }}</a></div>
<div class="content-card overflow-hidden"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>{{ __('inventory.warehouse.code') }}</th><th>{{ __('inventory.warehouse.name') }}</th><th>{{ __('inventory.warehouse.address') }}</th><th>{{ __('inventory.warehouse.tracked_skus') }}</th><th>{{ __('inventory.warehouse.status') }}</th><th class="text-end">{{ __('inventory.warehouse.actions') }}</th></tr></thead><tbody>
@forelse($warehouses as $warehouse)<tr><td class="fw-semibold">{{ $warehouse->code }}</td><td>{{ $warehouse->name }}</td><td>{{ $warehouse->address ?: '-' }}</td><td>{{ $warehouse->stocks_count }}</td><td><span class="badge rounded-pill {{ $warehouse->is_active ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $warehouse->is_active ? __('inventory.warehouse.active') : __('inventory.warehouse.inactive') }}</span></td><td class="text-end"><a href="{{ route('inventory.warehouses.edit',$warehouse) }}" class="btn btn-sm btn-outline-primary">{{ __('inventory.warehouse.edit') }}</a><form method="POST" action="{{ route('inventory.warehouses.destroy',$warehouse) }}" class="d-inline" onsubmit="return confirm(@js(__('inventory.warehouse.confirm_delete')))">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">{{ __('inventory.warehouse.delete') }}</button></form></td></tr>@empty<tr><td colspan="6"><div class="erp-empty"><i class="bi bi-buildings"></i>{{ __('inventory.warehouse.empty') }}</div></td></tr>@endforelse
</tbody></table></div>@if($warehouses->hasPages())<div class="p-3 border-top">{{ $warehouses->links() }}</div>@endif</div>
@endsection
